version: '3.8'
services:
  postgresdb:
    image: postgres:14
    container_name: postgres-blog
    env_file:
      - ./.env
    command: -p 5430
    networks:
      testnet:
        ipv4_address: 172.26.0.3
    volumes:
      - django_blog_db:/var/lib/postgresql/data
    ports:
      - 5430:5430
    expose:
      - 5430
  web:
    build: .
    container_name: 'blog'
    volumes:
      - static_django_blog:/blog/staticfiles
  web_migrate:
    extends:
      service: web
    container_name: 'migrate'
    command: > 
      /bin/sh -c "python3 manage.py migrate --force-color -v 3
      && python3 manage.py loaddata api/fixtures/db.json
      && python3 manage.py collectstatic"
  web_run:
    extends:
      service: web
    container_name: 'blog_run'
    command: gunicorn blog.wsgi:application --bind 0.0.0.0:8000
    networks:
      testnet:
        ipv4_address: 172.26.0.2
    expose:
      - 8000
  cache:
    image: redis
    container_name: redis-django-blog
    ports:
      - 6370:6370
    command: --port 6370
    networks:
      testnet:
        ipv4_address: 172.26.0.5
  nginx:
    build: ./nginx
    container_name: nginx-django-blog
    volumes:
      - static_django_blog:/blog/staticfiles
    networks:
      testnet:
        ipv4_address: 172.26.0.4
    ports:
      - 1337:80
    depends_on:
      - web_run


networks:
  testnet:
    external: True
volumes:
  static_django_blog:
    external: True
  django_blog_db:
    external: True