version: '3.8'
services:
  web:
    build: .
    container_name: 'blog'
    volumes:
      - .:/blog
  web_migrate:
    extends:
      service: web
    container_name: 'migrate'
    command: > 
      /bin/sh -c "python3 manage.py migrate --force-color -v 3
      && python3 manage.py loaddata api/fixtures/db.json"
  web_run:
    extends:
      service: web
    container_name: 'blog_run'
    command: gunicorn blog.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000